// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace UsageTest
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidMyPackageString = "2f7ada1b-2c5a-43b0-94bf-c965165aa69f";
        public static Guid guidMyPackage = new Guid(guidMyPackageString);

        public const string guidMyPackageCmdSetString = "a19af14e-c6cf-4f7d-a704-75d3f8959afe";
        public static Guid guidMyPackageCmdSet = new Guid(guidMyPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int Command1Id = 0x0100;
    }
}